# Generated by Django 2.0.3 on 2018-10-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_evententry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evententry',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventEntry',
        ),
    ]
