# Generated by Django 2.0.3 on 2018-10-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_event_evententry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evententry',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='evententry',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='evententry',
            name='datetime_created',
        ),
    ]
