# Generated by Django 2.0.3 on 2018-10-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181010_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evententry',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventEntry',
        ),
    ]
